services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb_container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=timescale_practice
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
